# Site settings
title: YB
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yansal.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  yansal

# Build settings
markdown: kramdown
